/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class server_processing_CallingCobol */

#ifndef _Included_server_processing_CallingCobol
#define _Included_server_processing_CallingCobol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     server_processing_CallingCobol
 * Method:    adaptor
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_server_processing_CallingCobol_adaptor
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
