/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CallingCOBOL */

#ifndef _Included_CallingCOBOL
#define _Included_CallingCOBOL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CallingCOBOL
 * Method:    adaptor
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CallingCOBOL_adaptor
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
